# Generated by Django 4.2.10 on 2024-02-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='POsts',
            new_name='Post',
        ),
    ]
